SOHU-Co/kafka-node

- lib/highLevelProducer.js
Fixes error in `HighLevelProducer#createTopics` when `topics` parameter is single topic name.
> fix HighLevelProducer.createTopics

- lib/consumer.js
If the consumer is not in ready state, the addTopics() method will try again in 100ms. However the fromOffset argument was accidentally dropped from the retry.
> fromOffset no longer dropped in addTopics if consumer is not yet ready

- README.md
- lib/client.js
- lib/codec/index.js
- lib/codec/snappy.js
- lib/consumer.js
- lib/producer.js
- lib/protocol/protocol.js
- package.json
- test/test.consumer.js
- test/test.offset.js
- test/test.producer.js
Support for handling compression in both consumer and producer. On the consumer side it's handled transparently, for producers there's a new property in the payload (`attributes`) that can be set to 0, 1, or 2 (defaults to 0).
This PR also adds support for consumer.encoding which can be used to control how values are returned. Previously it was only possible to retrieve a stringified version of the value which destroyed binary encodings (like msgpack). The default is "utf8" which should match the previous behavior.
Fixes https://github.com/SOHU-Co/kafka-node/issues/27
> Handle snappy & gzip compression

- lib/client.js
- package.json
Change implemention of createTopic api when async is false. Priviously
it was done by checking the existence of topic in zookeeper, and now
it retry to sent metadata requests util the topic is actually available.
> Refactor producer.createTopics

- lib/client.js
The addition solves the problem of never-called callback function passed to, for example, `Producer#send`.
Before there was no connection between socket (connection to broker) and callbacks passed to methods which interact with Broker and expect response. So once Broker died (OOM, stopped by supervisor, whatever), client started infinite reconnect attempts.
The point is callback should be called once we get socket error like `ECONNRESET` / `ECONNREFUSED`. This way module user can handle error in place where he calls some method (instead of handling client 'error' or 'close' events).
> improve callback queue

- lib/client.js
- lib/consumer.js
- lib/highLevelConsumer.js
- lib/zookeeper.js
- package.json
- test/test.consumer.js
We should ignore it when get null from queue, this may happen when a broker is down and it's callback queue is cleared, but there is some buffer still parsing. related issue #156
> More improments for callabck queue

- lib/highLevelProducer.js
- lib/producer.js
- test/test.producer.js
Currently the API does not offer a way to set the key on an outgoing
message. This resolves that hole by allowing devs to pass in Message
structs directly and have them be sent to the broker.
Has a test that passes.
> Support sending a Message struct from the producer

- lib/protocol/protocol.js
Message values may be null. If we get a null, pass -1 for the length.
> Allow null message values

- lib/client.js
- lib/protocol/protocol.js
- package.json
- test/test.producer.js
If a message is not a buffer or string, then convert it to string with
`toString()`
> Support more message type

- CHANGELOG.md
- lib/client.js
- lib/highLevelConsumer.js
> Fix #169: When paused why try to fetch every 1000 ms?

- lib/zookeeper.js
This avoids a race condition in `checkPartitionOwnership`, where another instance may create the node initialized to `null`, so the node will exist, it will try to get its contents but will fail in the comparison `consumerId !== data.toString()` since data may be `null`.
> Initialize partition owner with consumerId

- lib/client.js
- lib/highLevelConsumer.js
- lib/protocol/protocol.js
This should fix issue #175. When the client get `NotLeaderForPartition`
error, that means the leader for the partition has changed, so it emit a
`brokersChanged` event, consumer and producer listen this event and
refresh topic metadata.
> Refresh metadata after auto rebalance among brokers

- CHANGELOG.md
- README.md
- example/producer.js
- lib/client.js
- lib/highLevelProducer.js
- lib/producer.js
- package.json
- test/test.producer.js
When the requireAcks is set to 0, producer will return `{ result: 'no
ack' }` after sending produce request.
> Producer support `requireAcks` option

- lib/client.js
This pull request simply fixes a single typo.
Edit: Added another commit that fixes a few other typos.
> Typo in error message

- lib/zookeeper.js
I got kafka-node:zookeeper Exception: CONNECTION_LOSS[-4] error
sometimes, and the error sliently swallowed so it can not be catched
I thought the error should be thrown instead of been sliently swallowed.
> fix: emit the error instead of slient swallow it

- CHANGELOG.md
- lib/consumer.js
- lib/highLevelConsumer.js
Add callback function to consumer.autoCommit to prevent program from
crashing when broker is not available.
> Fix: add callback to consumer.autoCommit method

- README.md
Add default autoCommit to HighLevelConsumer documentation so people know that they can set it to something else.
> Add autoCommit default value to doc

- lib/client.js
- lib/zookeeper.js
When using the `HighLevelConsumer`, the `ZooKeeper` client continues to recursively run `listConsumers` even after closing.
This causes an exception to be thrown if the process does not exit immediately.
> Exit cleanly from HighLevelConsumer

- package.json
- Fixes installation problem when using iojs 2 (due to nan dependency in snappy
3.0.8).
- This is a proposed fix to issue: https://github.com/SOHU-Co/kafka-node/issues/204
> Update snappy dependency to ^3.2.0

- lib/highLevelProducer.js
```js
p.partition = p.partition || self.client.nextPartition(p.topic);
```
will override p.partition with nextPartition() for a value of 0 because 0 is falsy.
This fixes it.
> fix(HighLevelProducer): allow sending to partition 0

- package.json
2 snappy unit tests still passing after upgrade
close #241
> upgrade snappy depend to 4.0.0

- lib/protocol/protocol.js
Allow for null keys.  We ran into issues running mirrormaker where the keyedmessages on the source broker had blank strings for the key instead of null.  This caused all the messages to be hashed to the same partition when mirrormaker republished.
> encode -1 when key is empty or is null

- lib/highLevelConsumer.js
for multiple consumers it can be handy to be able to specify our own meaningful name for monitoring purposes.
> add in the ability to supply our own id for the consumer

- lib/zookeeper.js
fix for issue #269, rename the variable callback to cbb to stop the callback from failing.
to reproduce create multiple high level consumers very quickly, the error produced is 
```
/opt/kafka-http-proxy/node_modules/kafka-node/node_modules/async/lib/async.js:43
if (fn === null) throw new Error("Callback was already called.");
^
Error: Callback was already called.
at /opt/kafka-http-proxy/node_modules/kafka-node/node_modules/async/lib/async.js:43:36
at /opt/kafka-http-proxy/node_modules/kafka-node/node_modules/async/lib/async.js:718:17
at /opt/kafka-http-proxy/node_modules/kafka-node/node_modules/async/lib/async.js:167:37
at /opt/kafka-http-proxy/node_modules/kafka-node/lib/zookeeper.js:137:45
at /opt/kafka-http-proxy/node_modules/kafka-node/node_modules/node-zookeeper-client/index.js:165: …
```
> Fix/duplicate callback issue #269

- README.md
- kafka.js
- lib/client.js
- lib/highLevelProducer.js
- lib/partitioner.js
- lib/producer.js
- test/test.partitioner.js
- test/test.producer.js
This adds different partitioning strategies (random, cyclic, keyed) to producers, so that it makes it easier to apps using producers to utilise all partitions of the topics.
> Producer partitioners

- .gitignore
- README.md
- lib/client.js
resolve #313 resolve #311 resolve #300 
Fix on error handling after PR #262
> Fix client socket when closing and error handling

- lib/consumer.js
- lib/highLevelConsumer.js
Currently `commit()` method in consumer and high level consumer accepts two arguments. And it does not handle case with one argument, if I'm correct. This PR fixes the issue.
Fixes #296
> Make `commit()` handle case when only callback is passed

- lib/codec/snappy.js
- package.json
There will still be errors shown (below) for environments without the right dependencies to install snappy but the `npm install` finishes successfully.
```
npm info lifecycle snappy@4.1.2~install: snappy@4.1.2
> snappy@4.1.2 install /kafka-node/node_modules/snappy
> node-gyp rebuild
gyp info it worked if it ends with ok
gyp info using node-gyp@3.3.1
gyp info using node@5.10.0 | linux | x64
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at failNoPython (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:401:14)
gyp ERR! stack     at /usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:330:11
gyp ERR! stack     at F …
```
> Fix #273 by making snappy an optional dependency

- README.md
Add reference to `options.id` which can be used to specify own consumer Id.
Follows #295
> Update documentation for `HighLevelConsumer`

- lib/client.js
While refreshing metadata it's possible for the socket connection to be closed with had_error = true but this.error = null.
This leads to clearCallbackQueue being run with a 'null' error.
In turn, this leads to the loadMetadata callback in refreshMetadata being invoked with err = null and resp = undefined thus it tries to extract an error with:-
err = err || resp[1].error 
Since resp is undefined due to the above then it leads to an uncaught TypeError "Cannot read property '1' of undefined".
(Extra debugging added:)
1. Consumer closes the connection
2016-02-04T14:11:28.026Z - debug: kafka-node:Consumer connection closed
2. socket had_error = true but this.error = null
2016-02-04T14:11:28.026Z - debug: kafka-node:Client socket had_error: true
2016-02-04T14:11:28.026Z - debug: …
> Fix: TypeError: Cannot read property '1' of undefined

- README.md
This should help with issues like #339 when people copy and paste from the examples.
> Fix fetchMaxBytes in example to match the default

- lib/protocol/protocol.js
> Fixes protocol value checking before converting to string

- lib/highLevelConsumer.js
- test/test.highlevelConsumer.js
If there is done event fired on high level consumer 
after "rebalanced" event 
but before "updateOffsets" method in "rebalanced" event handler of HighLevelConsumer being fulfilled 
then that will trigger fetching all messages from zookeeper for the partition requested.
This is happening because at that stage owned partitions of HighLevelConsumer is set to 0.
This PR make sure "rebalancing" flag is set to "false" only after offsets are updated with the values from zookeeper and hence any "fetch" call before that will be ignored.
This issue can happen when rebalance occurs frequently in short time due to various reasons like network interruptions or addition or removal of a consumer with same group id.
> Prevent fetch before offset are updated after high level consumer rebalance

- lib/consumer.js
- lib/highLevelConsumer.js
- test/test.consumer.js
Removes unused `autoCommitMsgCount` option.
Resolves #363
> Remove unused config resolves #363

- .travis.yml
- README.md
- package.json
Adds code coverage reporting using Coveralls. This uses the existing code coverage tools, it just adds a final step to Travis CI to report the lcov.info information to coveralls on success.
To see what the coveralls tool will look like, you can see [my fork](https://coveralls.io/github/lightswitch05/kafka-node).
Note: To enable coveralls integration with this original repo, it does require you to log into [coveralls.io](https://coveralls.io/) and allow github integration. The account is free, but I understand if that isn't something you want.
> Added coverage reporting with coveralls.

- lib/client.js
- test/test.client.js
To reproduce this issue locally.
Update `docker-compose.yml`:
```yml
version: '2'
services:
zookeeper:
image: wurstmeister/zookeeper
ports:
- "2181:2181"
kafka:
image: wurstmeister/kafka:latest
ports:
- "9093:9093"
depends_on:
- zookeeper
environment:
KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
KAFKA_LISTENERS: "SSL://:9093"
KAFKA_ADVERTISED_LISTENERS: "SSL://${KAFKA_ADVERTISED_HOST_NAME}:9093"
KAFKA_SSL_KEYSTORE_LOCATION: "/var/private/ssl/certs/server.keystore.jks"
KAFKA_SSL_KEYSTORE_PASSWORD: "password"
KAFKA_SSL_KEY_PASSWORD: "password"
KAFKA_SSL_TRUSTSTORE_LOCATION: "/var/private/ssl/certs/server.truststore.jks"
KAFKA_SSL_TRUSTSTORE_PASSWORD: "password"
KAFKA_CREATE_TOPICS: "RebalanceTopic:3:1"
KAFKA_SECURITY_INTER_BROKER_PROTOCOL: "SSL"
volumes:
- …
```
> Fixes #427 stop relying on deprecated host and port config from kafka

- test/test.offset.js
- test/test.zookeeper.js
Added more tests involving offset and zookeeper.
Coverage before new tests:
```
Statements   : 84.3% ( 1681/1994 )
Branches     : 67.07% ( 495/738 )
Functions    : 85.25% ( 393/461 )
Lines        : 85.58% ( 1626/1900 )
```
Coverage after new tests:
```
Statements   : 85.61% ( 1707/1994 )
Branches     : 68.7% ( 507/738 )
Functions    : 87.2% ( 402/461 )
Lines        : 87% ( 1653/1900 )
```
> Added more unit tests for offset and zookeeper.

- lib/errors/FailedToRegisterConsumerError.js
- lib/highLevelConsumer.js
- lib/zookeeper.js
- package.json
- test/mocks/mockZookeeper.js
- test/test.highlevelConsumer.js
- test/test.zookeeper.js
> Fix issues with zookeeper connection loss recovery

- lib/utils.js
Leaving the `validateTopics` topics function as it is because I believe it is meant for validating the topics coming from the `send()` function. Not sure, though.
`validateCreateTopics` contains following checks which are similar to what is been done for Kafka here [https://github.com/apache/kafka/blob/trunk/core/src/main/scala/kafka/common/Topic.scala]
- check if the topic is empty.
- check if the topic is . or ..
- check if the topic length is greater than 249 characters.
- check if the topic, is not ASCII alphanumeric.
> Adding new util function for topics validations

- lib/client.js
This is my observation while playing with createTopics function. I later realised that topic names which I am creating contains special characters such as :,// etc which is causing the issue. I tried without them and it works. It does work with other number and string combinations so no test required for that.
Hope this PR is help.
> Kafka topics should not contain special characters

- lib/assignment/range.js
- lib/client.js
- lib/highLevelConsumer.js
- lib/protocol/protocol.js
- lib/utils.js
- lib/zookeeper.js
`for...in` is dangerous in JavaScript. When used, one must use the hasOwnProperty() test:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/for...in#Iterating_over_own_properties_only
Example: kafka-node kept crashing when used together with another library that defined a polyfill for `Object.values()` https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/values:
``` javascript
if (!Object.values) {
Object.prototype.values = function (obj) {
return Object.keys(obj).map(function (key) {
return obj[key];
});
};
}
```
All the `for .. in` loops in kafka-node would iterate over an additional property `values`, which will then make kafka-node to crash.
Note: I tried to run the tests as documented (including installing Docker), but the …
> for...in loops must check for hasOwnProperty

- package.json
Before nested-error-stacks v2, building nested errors in node v7 did not work correctly. Upgrading the dependency will allow kafka-node to avoid those problems in node v7
> Upgrade nested-error-stacks to v2 for node v7 support

- lib/highLevelConsumer.js
- package.json
- This proposal is to address https://github.com/SOHU-Co/kafka-node/issues/541 (HighLevelConsumer leaving partitions without owner on multiple consumers startup). After doing several tests and observations, I believe this (bad) resulting scenario may be caused by race conditions of several consumers trying to consume same partitions and library not handling correctly the retries. Therefore the idea is to allow the rebalance retries to be configurable for each scenario. Particularly, I got good results when setting each consumer with a different (randomised) cycle of retry, to avoid collisions on attempts.
- The change is not breaking at all.
- Also is included a bump on retry library (used on rebalancing action) to version 0.7.0 which introduces a couple of bugfixes. The most important …
> Allow configuration of rebalance retry strategy on HighLevelConsumer

- lib/highLevelConsumer.js
in `HighLevelConsumer.updateOffsets` autoCommit was being called
regardless if the connected topics were updated or not, causing
autocommit to be called frequently with the same offsets already in
place
> reducing autocommit fires when consumer is idle

- README.md
- lib/offset.js
- test/test.offset.js
when offset isnt ready need to call proper method in setTimeout.
> Fix bug in Fetch earliest offsets

- CHANGELOG.md
- README.md
- lib/assignment/range.js
- lib/assignment/roundrobin.js
- lib/client.js
- lib/consumer.js
- lib/consumerGroup.js
- lib/consumerGroupHeartbeat.js
- lib/consumerGroupMigrator.js
- lib/consumerGroupRecovery.js
- lib/highLevelConsumer.js
- lib/logging.js
- lib/zookeeper.js
- logging.js
- test/test.logging.js
Kafka-node should be easier to integrate into larger applications. A
large part of this is log handling. Debug's log output configuration is
not really usable for application developers and does not allow
filtering of log messages by level.
This PR adds the ability to set logger providers while retaining the
current default logging strategy: debug.
Fixes #595
> Allow custom logging implementations

- package.json
Dependencies should frequently be checked for security vulnerabilities as part of the build job. This commit adds the Node Security Platform CLI tool (`nsp`) to the build process. Dependency verification is really fast, so it is not slowing down the build / local tests.
Also, there are currently no known vulnerabilities 🍹
> Dependencies should be checked for security vulnerabilities

- lib/protocol/protocol.js
This information is useful to keep track of the consumer status.
> Passing highWaterOffset both to onMessage and onDone

- lib/client.js
- package.json
- start-docker.sh
`Buffer#slice()` in node is extremely slow and should avoid using it! Unfortunately, we didn't realize it when create this project. So, we should have a plan to improve the performance of this module:
- Step 1: Using `BufferList`(bl) instead of raw Buffer to avoid calling `Buffer#slice()`.
I have a patch for this module, and tested it in production. In my case, I have reduced CPU usage from **70%** to **50%**, and memory usage from **400m** to **200m**, and increased throughput from **200k/min** to **400k/min**. 
- Step 2: Replace `binary` module. The module is 5 years old and have not be maintained for 5 years! `kafka-node` is heavily depended on `binary` but unfortunately `binary` used `Buffer#slice()`, a lot.
This patch complete `Step 1`,  and I hope someone else could help me with the …
> Improve performance

- lib/client.js
Found a bug on data handling. Buffer could be empty between new incoming data arrived and `setImmediate()` callback be called
> Check buffer length before processing

- README.md
- kafka.js
- lib/client.js
- lib/consumerGroup.js
- lib/errors/TimeoutError.js
- lib/highLevelConsumer.js
- lib/kafkaClient.js
- lib/wrapper/BrokerWrapper.js
- test/helpers/child-cg-kafka-client.js
- test/mocks/mockSocket.js
- test/test.consumerGroup.js
- test/test.highlevelProducer.js
- test/test.kafkaClient.js
- test/test.rebalance.js
> Connect directly to kafka brokers using new client closes #666

- README.md
- docker/createTopic.js
- lib/baseProducer.js
- lib/client.js
- lib/consumerGroup.js
- lib/protocol/protocol.js
- test/test.baseProducer.js
- test/test.consumerGroup.js
* Fix issue where a specified key attribute was not in the message
* Fix issue where a non null or undefined falsey value (such as an empty string) was not able to be saved into the message
* Preferred encoding for the key can be defined by the `keyEncoding` option on any of the consumers
* Fix issue where Buffer was not able to be saved into the message
> Fix message key

- lib/client.js
Publishing (KafkaClient) / Consuming (KafkaClient and ConsumerGroup) to a "fresh" broker (no topics), there are two issues:
- I receive "LeaderNotAvailable"
- A null reference exception happens at client.js#541
This fixes the null reference exception.
I still receive "LeaderNotAvailable", followed by "BrokerNotAvailableError: Could not find the leader" and then eventually publishing starting working so there's some timing issue, but I'll look into that separately.
Signed-off-by: Michael Haan <haanmd@gmail.com>
> "this" should be "self"

- package.json
Breaking is dropped support for older nodes (and new snappy version).
I haven't tested this, though
https://github.com/kesla/node-snappy/blob/master/CHANGELOG.md
> Upgrade snappy

- lib/consumerGroupStream.js
Added missing callback function in the code. 
This is needed when stream.close() function is called and subsequent clean up happens.
> Added missing callbacks in the commit()

- lib/consumerGroupStream.js
I ran into a situation where I pulled multiple messages of a `ConsumerGroupStream` in short succession, after which I reached the high water mark. The offset commit was triggered by the first read of the stream, with subsequent commits "throttled" and pushed to a queue. However, because no additional messages were read from the stream, another call to `stream.commit` never happens, with the commit stuck in the queue. This, in turn, lead to messages being consumed more than once.
To solve the issue I added a check to flush anything in the queue at the tail end of the throttling time-out.
I looked for a place to add tests, but couldn't find any for `ConsumerGroupStream` at all. Before I put a lot more effort in I thought I'd check whether this has any chance of getting merged at all! Also …
> Flush queued commits of ConsumerGroupStream on tail end of auto-commit time-out

- lib/consumerStream.js
I ran into an issue where I needed `ConsumerStream` to start consuming from a certain offset. I passed it as a payload during construction, and `fromOffset: true`. However, there wasn't any code handling this.
For the implementation I looked at how it's handled in `Consumer`, to stay consistent.
> Fix fromOffset option for ConsumerStream

- lib/client.js
- test/test.client.js
Fixes point 1 of Issue #859 
Checks if the `listener.security.protocol.map` property is present in the broker metadata. If it is: it will apply the mapping from listener name to security protocol used before checking whether a listener uses the protocol desired by the kafka-node client.
For point 2 it currently still requires the endpoint to be used by kafka-node to be listed first.
> Add support for brokers separating external and internal traffic (introduced in KIP-103)

- lib/client.js
If we `pause()` and then later `resume()` a consumer within a 'done' callback, we can get into a situation where the consumer doesn't actually resume because `sendToBroker` bails out early (because `broker.socket.waiting` is still `true` while the 'done' callback is being invoked, so the fetch request gets thrown away).
To work around this I've had to use `setImmediate(() => consumer.resume())` to schedule the resume() to occur after the `socket.waiting` flag has been reset. It works well enough, but it's not very intuitive.
This change simply moves the `socket.waiting` reset to occur before we fire off the decoder & associated callbacks. I _think_ this is pretty low risk, but perhaps you can think of a reason why we wouldn't want to do this.
Something else to consider: it can be somewhat …
> Clear socket.waiting before invoking callbacks

- lib/kafkaClient.js
We should support kafka-node for IPv6 as well. I've updated the parseHost function to parse both IPv4 and IPv6 addresses. According to RFC 3986 (https://tools.ietf.org/html/rfc3986), an IPv6 address is supposed to be wrapped by brackets and separated with port number by a colon. 
eg. [2001:bd4:32:4d21:225d:1f22:113:2535]:9092
This an example of presented IPv6 address a client is supposed to receive as the kafkaHost option.
> Support for IPv6

- lib/consumerGroup.js
This handles case where more consumers join than their are partitions.
when this occurs, one of the consumers may receive no partitions, and
this topicPayloads variable still contained reference to their previous
partition assignment.
> Clear topic payload if no partitions are assigned

- lib/consumerGroupStream.js
The commit at https://github.com/SOHU-Co/kafka-node/commit/abc160986765ebf94b121d56cadaa4a3d426559a introduced a bug
where the offset was incremented at the wrong location.
commitQueued then expected the offset committed to match what is currently in the queue, and that commit broke this.
This results in commit records never being correctly removed from the commitQueue, leading to
weird behavior when committing and messages being consumed twice when rebalances occur relating
to committing stale offsets.
> Fix Stale Commit Queue for ConsumerGroupStream

- README.md
- lib/consumerGroup.js
- lib/consumerGroupStream.js
Should resolve #787
If auto commit is true, commit before we rejoin the group on a rebalance
According to the kafka protcol, commits are allowed during this stage, as the generation ID has not been bumped yet.
If auto commit is disabled, implementors need a way to decide what to commit, so an onRebalance option was added.
Implementors can perform commits during this method and call back when done to finish the rebalance.
> auto commit and add event for rebalance

- lib/admin.js
- lib/baseProducer.js
- lib/client.js
- lib/consumer.js
- lib/consumerGroup.js
- lib/consumerGroupMigrator.js
- lib/highLevelConsumer.js
- lib/kafkaClient.js
- lib/offset.js
- lib/partitioner.js
- lib/zookeeper.js
Classes that were missing ctors would be missing initialization code for Domains, which could introduce bad bahavior. It's overall the responsible thing to do to always execute your super ctor.
Other fixes:
1) noAckBatchOptions in KafkaClient was not being read correctly from options
2) Use EventEmitter directly as name instead of events.EventEmitter so that IDE code completion behaves correctly
3) Fix some typos/case incorrectness
4) Raise Client max event listeners, as high volume publishing while a broker is not ready schedules lots of 'onBrokerReady' events which triggers nodes memory leak warning. Give a higher threshold.
5) Even though Partitioner has no body, still added super ctor for correctness, so if a body is added in the future, bugs are prevented.
6) Clean up some code style …
> Add missing super ctor calls across code base, fix small quirks

- lib/consumerGroup.js
If the onRebalance function yields a value, it would be reflected
into the waterfall and move the callback to the 2nd parameter.
see #918
> Wrap ConsumerGroup.onRebalance to avoid waterfall bug

- README.md
I added SSL to the options for the KafkaClient API. I assume they are only for Kafka 0.9+ like they are for the Client API.
I'd also like to make it explicit that they are being passed straight to the Node TLS module so users can get a full list of things they can set on the object, but I'm not sure if Client is handling that like KafkaClient seems to be.
> Update docs to specifiy sslOptions in kafkaClient options

- lib/consumerGroup.js
If the response is missing key elements, or sends an invalid protocol,
we need to error out. Invalid protocols before was throwing JS errors.
I'm not sure WHY I had this occur, but I had processes crashing in production due to this.
> Validate joinGroupResponse has some required elements

- lib/kafkaClient.js
- test/test.kafkaClient.js
this should help with some of the intermittent failures.
> Do not attempt to refreshBrokerMetadata when client is closing

- lib/consumerGroupStream.js
This is to emit `connect` event for consumer group stream.
> Emit connect event for consumer group stream

- lib/kafkaClient.js
- lib/wrapper/BrokerWrapper.js
It's possible to get a synchronous exception if `apiSupport` is empty for some reason. We should yield an error explicitly in this case.
> Yield error if apiSupport is empty on a ensured ready broker

- lib/client.js
- lib/consumerGroup.js
In ConsumerGroup refresh metadata errors weren't being correctly emitted as 'error'.
- Creates an error when metadata refresh request returns an error.
- Fixes emit to send error event to 'error'.
> Fix error event in recoverFromBrokerChange

- .eslintignore
- package.json
- types/index.d.ts
- types/kafka-node-tests.ts
- types/tslint.json
* Add `tslint` to `package.json`
* Add `tslint-config-semistandard` library to `package.json` to align coding style to the main project
* Add tslint configuration file to `types` folder.
* Reformat `.ts` files.
* Add `test:ts` script for devevlopment and testing.
* Extend `test` node script with `test:ts`.
New `npm` script: `npm run test:ts`.
> Add tslint, tslint-semistandard for typescript linting and reformat ts files

- lib/highLevelConsumer.js
- env
- kafka version: 0.8
- kafka-node version: ^2.3.0
- consumer process count: 16 (in different pc)
- partition count: 46
- reproduce:
- consumer1 and consumer2 is in different processes
- consumer1 is owner of partition1+2, `consumerChanged`, rebalancing and `rebalanceAttempt`: 
- determining to own partition3+4
- update ZK partition3 success
- update ZK partition4 failed
- retry rebalanceAttempt
- consumer2 registered when consumer1 is rebalancing, start to rebalancing and `rebalanceAttempt`: 
- determining to own partition3
- update ZK failed by: `FailedToRebalanceConsumerError`:`NODE_EXISTS`
- retry continuously..cannot emit rebalanced
- consumer1: retry `rebalanceAttempt`
- found consumer2 and determining to own partition4
- update ZK partition4 success
- rebalanced
- result: …
> HighLevelConsumer throw FailedToRebalanceConsumerError: NODE_EXISTS when rebalancing

- README.md
- lib/admin.js
- lib/errors/NotControllerError.js
- lib/kafkaClient.js
- lib/protocol/protocol.js
- lib/protocol/protocolVersions.js
- lib/protocol/protocol_struct.js
- test/mocks/mockSocket.js
- test/test.kafkaClient.js
This is a first attempt at adding support for the create topics request. I have been wanting this for a while since I work on some "management" tools for Kafka. Most other Kafka clients in other languages also seem to rely on the "metadata" solution.
This supports specifying number of partitions and replication factor. Explicit replica assignments and config entries are left out for now.
A create topic request must be sent to the controller. To find the current controller, this also adds a version 1 metadata request, which includes the controller Id in the response.
There are a couple of things that are less-than-optimal and could use some input for improvement:
- Added a "V2" suffix to resolve the conflict with current versions of `createTopics(..)` and `loadMetadataForTopics(..)`.
- …
> Add create topics support

- lib/kafkaClient.js
Small fix in addition to the previous PR. Check for null or undefined in metadata response instead for cases when broker with id "0" is controller.
> Fix controller check when controller id is 0

- .travis.yml
- README.md
- docker-compose.yml
- docker/docker-compose.0.10.yml
- docker/docker-compose.0.11.yml
- docker/docker-compose.1.0.yml
- docker/docker-compose.1.1.yml
- docker/sasl/sasl.conf
- docker/start-kafka.sh
- lib/client.js
- lib/errors/SaslAuthenticationError.js
- lib/errors/index.js
- lib/kafkaClient.js
- lib/protocol/protocol.js
- lib/protocol/protocolVersions.js
- lib/protocol/protocol_struct.js
- lib/wrapper/BrokerWrapper.js
- test/test.client.js
- test/test.kafkaClient.js
Still plenty more to do here (honestly, it's a bit of a mess in places), but thought I might open this up for comment.
We have a pressing need for dumb authentication in our Kafka cluster(s) to work around some infrastructure issues and kafka-node's support for TLS client certs isn't an option in the short term. Our immediate needs would be met with basic support for SASL/PLAIN, but obviously kafka-node doesn't support SASL -- just wanted to prove to myself that it was fairly trivial to hook up something simple. So this is my whirlwind prototype.
Very, very briefly verified against a local Kafka instance configured with a SASL_PLAINTEXT listener, seems to work -- just barely. 😅 
Support for SASL/GSSAPI & SASL/SCRAM-SHA-{256,512} are lower on my list of priorities, but would look pretty …
> WIP: basic support for SASL/PLAIN

- README.md
- lib/client.js
- lib/offset.js
- test/test.offset.js
References #558, #954
offset#fetchCommits gets the latest committed offsets from zookeeper. This pull request adds offset#fetchCommitsV1 functionality for fetching commits from the brokers, which aligns with how ConsumerGroup commits are stored.
Current implementation uses the same data structure as an input that offset#fetchCommits uses and converts it to the V1 format.
> Add offset#fetchCommitsV1 functionality and tests

- lib/kafkaClient.js
@aikar had a relevant comment on https://github.com/SOHU-Co/kafka-node/commit/a3653ba2d75a180be1e35f25be66cae0c9dcaa1c#commitcomment-29823455, that any longpolling argument should be passed. This is for any future code that would use `getBroker` and pass a value (currently none does).
> Pass longpolling argument

- types/index.d.ts
Method addTopics should be Generic because it could be misleading
if you don't know which type is returning callback value of the parameter
added.
> Fixing Consumer.addTopics type

- types/index.d.ts
Fixes a mistake in https://github.com/SOHU-Co/kafka-node/pull/1022 where I extended the wrong base interface
> Fix Typedefs for ConsumerGroupStreamOptions

- lib/kafkaClient.js
I've filed an issue regarding this commit, please refer to #1045. There is a race condition when broker is disconnecting and Kafka client sometimes still attempts to refreshBrokerMetadata when client is closing.
> Race condition when closing client, still attempt to refreshBrokerMetadata when client is closing

- lib/protocol/protocol.js
Kafka server may add partial message to the end of the message set with, for example, the following data:
```
MessageSet => [Offset MessageSize Message]
  Offset => 0
  MessageSize => 16216
Message => Crc MagicByte Attributes Key Value 
Crc => 0
  MagicByte => 0
  Attributes => 0
  Key => buffer of 0 bits
  Value => buffer of 0 bits
```
Instead of key/value the message is filled with 0 bits sequence. I couldn't find any special requirements on the format of the partial message, so maybe this is allowed behavior. But with such message from the server consumer continues decoding 0 bits, emits empty messages and the worst - it ends up with array of 0 offsets, e.g. [96510, 96511, 96512, 0, 0, 0, 0, 0], which leads to starting reading the next batch from 0 offset and gets into an infinite …
> Skip processing buffer after partial message detected

- README.md
- lib/protocol/protocol.js
- test/test.admin.js
Related to https://github.com/SOHU-Co/kafka-node/issues/984 and https://github.com/SOHU-Co/kafka-node/pull/985
I also added an entry for `createTopics` in the `admin` section of the README. Current README has the `createTopic` entry under `Producer`. Is this incorrect? I can revert if necessary.
> Fix describe groups

- lib/consumerGroupStream.js
Ensure that calling `commitQueued()` with `force=true` won't unbalance the `this.committing` true/false assignments.
Issue https://github.com/SOHU-Co/kafka-node/issues/1065
> ConsumerGroupStream: Only set committing=true if it can be set false later

- lib/highLevelConsumer.js
The setTimeout will hold a process open during process shutdown, even after the consumer has been closed.
By simply adding unref, node will no longer hold the process open for this task and allow it to shutdown correctly.
> Don't hang process on shutdown

- lib/client.js
- lib/consumerGroup.js
- lib/consumerStream.js
- lib/highLevelConsumer.js
- lib/kafkaClient.js
- lib/protocol/protocol.js
There was numerous risks with the fetch process resolved here.
1) Compressed messages, as mentioned in #298, would be guaranteed out of order
We resolve this by making fetch response buffering be handled through a chain
of executions, where one partition is not emitted until the previous one is done,
and able to be processed asynchronously.
This however introduces new risk as the system only dealt with synchronous
processing before, meaning 2 fetch buffers could not be processing at the same
time. But because it's now async, we could end up processing multiple.
We now need to guard starting a new fetch while one is still processing, to ensure
that a new fetch does not begin with stale offset data.
2) Fetch requests may start, and end up being long polling. This fetch result may
end up …
> Multiple fixes to message ordering and compression, Fixes #298

- types/index.d.ts
This seems to be necessary to allow configuring SSL options with ConsumerGroups in Typescript. It does work, but it's not part of the type.
> add sslOptions to ConsumerGroupOptions

- README.md
- lib/consumerGroup.js
This allows 'buffer' to be specified so that binary data to be consumed via ConsumerGroup without corruption, resolving issue #1131
> Allow specifying an encoding for ConsumerGroup (fixes #1131)

- README.md
- lib/admin.js
- lib/errors/InvalidRequestError.js
- lib/errors/index.js
- lib/kafkaClient.js
- lib/protocol/protocol.js
- lib/protocol/protocolVersions.js
- lib/protocol/protocol_struct.js
- lib/resources/index.js
- test/test.admin.js
- test/test.protocol.js
This PR adds support for DescribeConfigs, which allows a user to get the config entries for either a broker or topic (aka resource).
@hyperlink let me know if you have any opinions on data format input/output.
https://kafka.apache.org/protocol#The_Messages_DescribeConfigs
> add support for DescribeConfigs protocol

- README.md
- lib/errors/ApiNotSupportedError.js
- lib/errors/index.js
- lib/kafkaClient.js
- lib/protocol/protocol.js
- lib/protocol/protocolVersions.js
- test/test.kafkaClient.js
Adds support for providing config entries and explicit replica assignment
when creating new topics.
The existing create topic implementation has been cleaned up a bit,
as it didn't make use of the existing API support setup (it was fixed to protocol version 1).
As part of the cleanup, version 0 and 1 of the request is now supported.
The send controller request was also cleaned up a bit. A new function `sendRequestToBroker`
provides a more robust way to send requests to a specific broker now.
Create Topic tests now skips version 0.10. The new describe configs request is used to validate config entries. This request is supported from 0.11+.
This addition is backwards compatible.
> Add config entries and replica assignment to create topic

- types/index.d.ts
This PR is basically an update for type definitions. When using Avro schema serialization and desrialization, types of message key or value could be buffer. This is also a type catch-up for #932
> Type of message key could be Buffer when using Avro schema serialization and deserialization

- types/index.d.ts
This is a PR for #1035.
I have added definitions for the following `KafkaClient` options:
1. `idleConnection`
2. `maxAsyncRequests`
3. `sasl`
> TypeScript defs for idleConnection, maxAsyncRequests and sasl KafkaClient options

- types/index.d.ts
- types/kafka-node-tests.ts
ConsumerGroup and ConsumerGroupStream of kafka-node had already "connect" event .
But HighLevelConsumer in types/index.d.ts missed event for HighLevelConsumer.
> Add connect event for HighLevelConsumer in types/index.d.ts

- types/index.d.ts
This will allow using `consumer.once`, that will simplify testing.
> Made Producer & Consumer types as EventEmitter

- types/index.d.ts
The options object are passed along to the kafka client constructor, so this property goes here as well. Currently not possible to use sasl for consumers when using typescript.
> Add missing sasl property to consumergroup type

- lib/kafkaClient.js
- lib/protocol/protocol.js
- lib/protocol/protocolVersions.js
- test/test.admin.js
This fixes describe configs when requesting broker configs for clusters with  more than 1 broker.
Instead of sending all requests to all brokers, requests for broker configs are sent to the specific broker. T
opic config requests can go to any broker (follows the logic of the Java SDK).
Also reworked a bit to fit better into api support functionality.
Fixes #1172.
> Fix describe configs for multiple brokers (#1772)

- lib/baseProducer.js
- test/test.baseProducer.js
Make sure the ready event is emitted asynchronously so that it can be
caught by listeners.
Signed-off-by: Raymond Feng <enjoyjava@gmail.com>
> Fix ready event emitting for producers
