lib/client.js
=> Fix for #134

README.md, example/producer.js, lib/client.js, lib/consumer.js, lib/highLevelProducer.js, lib/producer.js, lib/protocol/protocol_struct.js, package.json, test/test.zookeeper.js
=> Make compression working with HighLevelConsumer & HighLevelProducer

lib/client.js, lib/consumer.js, lib/highLevelConsumer.js
Having to get the second parameter for an error is really confusing.
=> Change to send the errors as the first parameter.

README.md, kafka.js, lib/client.js, lib/offset.js
Add `ready`, `connect` events in Offset api to gain better usage, issue #149 
Optimize Client, only create 1 socket connection when initialize
Use `localhost:2181` as default zookeeper connection string
=> Improve Offset api & optimize

README.md, lib/consumer.js, test/test.consumer.js
Add `pauseTopics` and `resumeTopics` in Consumer. For issue #145
=> Pause resume topics

lib/client.js, package.json
=> Prevent emit error when clear callback queue

README.md, example/producer.js, kafka.js, lib/highLevelProducer.js, lib/producer.js, lib/protocol/protocol_struct.js, package.json, test/test.producer.js
Producer can send keyed message by create message with KeyedMessage(key,
value), related with #164
=> Export KeyedMessage

CHANGELOG.md, lib/client.js, lib/highLevelProducer.js, lib/producer.js, package.json
=> Refresh topic metadata in Producer when broker change

lib/client.js, lib/highLevelConsumer.js, lib/zookeeper.js
=> High level consumers should be able to recover a zk disconnect

lib/client.js, lib/highLevelConsumer.js
=> Kafka connectivity

lib/offset.js
Fixes small typo in `offset.js`.
=> Fix typo in offset.js

lib/partitioner.js, test/test.partitioner.js
=> fix bug where different partitoners where affecting others

lib/client.js
This PR is a workaround for a nodejs [socket issue](https://github.com/nodejs/node/issues/4417) I ran into last year.
=> Recreate broker sockets to work around nodejs socket issue #4417

test/test.zookeeper.js
Added more testing for zookeeper.
Coverage before this pull request:
Statements   : 79.17% ( 1543/1949 )
Branches     : 62.25% ( 442/710 )
Functions    : 76.82% ( 348/453 )
Lines        : 80.31% ( 1489/1854 )
Coverage after this pull request:
Statements   : 82.2% ( 1602/1949 )
Branches     : 64.65% ( 459/710 )
Functions    : 82.34% ( 373/453 )
Lines        : 83.39% ( 1546/1854 )
=> Added more unit tests for zookeeper.

lib/highLevelConsumer.js, lib/zookeeper.js, test/mocks/mockZookeeper.js, test/test.zookeeper.js
=> Springuper's partitions changed

lib/zookeeper.js, test/test.highlevelConsumer.js
=> Fix unscheduled rebalance

lib/client.js, lib/consumerGroupRecovery.js, test/test.client.js, test/test.consumerGroupRecovery.js
When broker becomes unavailable try to find a new coordinator and reconnect
=> Fixes #496 where exception is thrown when broker goes offline

lib/consumerGroup.js, test/test.consumerGroup.js
=> Fix leave group exception

lib/baseProducer.js, test/test.highlevelProducer.js
=> Normalize buildPayload data so messages are not missed 

README.md, lib/offset.js
-adding convenience function fetchEarliestOffsets
=> adding fetchEarliestOffsets to offsets prototype

CHANGELOG.md, package.json
See: https://docs.npmjs.com/files/package.json#files
=> Published NPM package should not contain testing and local development artifacts

README.md
=> Update loadMetadataForTopics doc to address common issues

README.md, kafka.js, lib/baseProducer.js, lib/highLevelProducer.js, lib/partitioner.js, lib/producer.js, test/test.partitioner.js
=> Custom partitioner

lib/client.js, package.json, start-docker.sh
reverting the bl changes since it's causing #669
=> Revert bl change

lib/protocol/protocol.js, test/test.consumer.js
Should solve issue #820 
Its probably possible to write better tests, happy for hints/suggestions on how to most easily do that
=> Include highWaterOffset with compression

lib/kafkaClient.js, test/test.kafkaClient.js
wrt #854 
cc: @thomaslee @rinzeb
=> updateMetadata should only replace topicMetadata in specific cases

lib/kafkaClient.js
=> Fixes #903 where initial metadata request failure stops KafkaClient connect retry

lib/consumerGroup.js, test/test.consumerGroup.js
This is related to https://github.com/SOHU-Co/kafka-node/issues/632
=> Implement 'addTopics' Functionality in consumerGroup Module

README.md, lib/consumerGroup.js
Record offsets at their current position, so that consumers are properly
registered to the topic.
=> Option to auto commit offsets on first join - Resolves #886

package.json, types/index.d.ts
=> Add ConsumerGroupStream typedef

lib/kafkaClient.js
One that was missed in https://github.com/SOHU-Co/kafka-node/commit/a9478a85e1cf79e59c4582b0b34ffa367034f009
=> Remove a noisy debug

lib/client.js, lib/kafkaClient.js
This is faster than using Objects as maps and will improve performance.
=> Use Map for Callback Queue

README.md, lib/consumerGroup.js, test/test.consumerGroup.js
fix bug: https://github.com/SOHU-Co/kafka-node/issues/999
=> fix:ConsumerGroup bug while removeTopics

lib/client.js, lib/kafkaClient.js
=> Give more information on why the broker was not found 

lib/consumerGroup.js, test/test.consumerGroup.js
=> Fix checking new partitions

README.md
create same variable name for topicsToCreate example.
=> Use same variable name for example

lib/consumerGroup.js, test/test.consumerGroup.js
A potential fix for https://github.com/SOHU-Co/kafka-node/issues/1144
=> Validation check for empty topic array

types/index.d.ts
Typings for `createTopics` and `loadMetadataForTopics`.
=> Add typings for create topic + fetch metadata

lib/kafkaClient.js
=> client.createTopics returns Error: No broker with id undefined
